version: '3.7'

services:
  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    restart: always
    user: "$UID:$GID"
    networks:
      - internal
      - external
    expose:
      - 3000
    ports:
      - 8000:3000
    volumes:
      - C:\Users\Josh\docker_data\gtp\grafana_data:\var\lib\grafana

  timescaledb:
    hostname: postgres
    image: timescale/timescaledb:latest-pg12
    restart: always
    networks:
      internal:
        aliases:
          - postgres
    expose:
      - 5432
    ports:
      - 55435:5432
    environment:
      - POSTGRES_DB=lab
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=Password01
    volumes:
      - C:\Users\Josh\docker_data\gtp\timescaledb_data:\var\lib\postgresql\data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  external:
  internal: